### ISSUE TITLE
Tutorial for getting started

### ISSUE THREAD

**Issue by gabrielfior** [streamingfast/sf-solana#65]
Hi guys,

apologies for the non-issue being raised.

I'm interested in fetching historical data from Solana using firehose. Is there a tutorial I should look specifically for Solana, or can I recycle the information from other chains, e.g. Ethereum (https://firehose.streamingfast.io/firehose-setup/ethereum/installation)?

Thanks

**Comment by gfrancqu** [comment]
hey @gabrielfior did you figured out how to get started ? I'm interested

**Comment by gabrielfior** [comment]
> hey @gabrielfior did you figured out how to get started ? I'm interested

I was able to fetch block data using this repo (https://github.com/streamingfast/substreams-solana-quickstart).
