### ISSUE TITLE
RPC poller does not set block time correctly on early blocks

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/sf-solana#72]
Syncing from genesis, the `head_block_time_drift` seems to be stuck on 1970-01-01 (0 unixtime)

```
$ curl -s  http://localhost:9102 |grep head_block
# HELP head_block_number
# TYPE head_block_number gauge
head_block_number{app="merger"} 28374
head_block_number{app="reader-node"} 28405
# HELP head_block_time_drift Number of seconds away from real-time
# TYPE head_block_time_drift gauge
head_block_time_drift{app="merger"} 1.7230446227405326e+09
head_block_time_drift{app="reader-node"} 1.723044622955191e+09
```

**Comment by sduchesneau** [comment]
At the beginning of the chain, there was no system clock on Solana at all.. they added that later.

Example: https://explorer.solana.com/block/1 (Timestamp: Unavailable)

It defaults to 0 unixtime. We can't retrieve or generate this data so there is no fix.
